import { Controller, Get, Header, NotFoundException, Param, Query, Res } from '@nestjs/common';
import { ApiOperation, ApiTags } from '@nestjs/swagger';
import type { Response } from 'express';
import { Public } from '../auth/decorators/auth.decorators';
import { buildSamplePdf } from './providers/sample-pdf';

/**
 * A stand-in document API, for demonstrating the pipeline without a real one.
 *
 * §1 of the brief allows this explicitly: the production document APIs are not yet known, so
 * rather than invent credentials for them, the registry points at these endpoints and the
 * whole job flow runs end to end against something real. Every route here returns an actual
 * PDF, not a placeholder, because the validation the worker performs is the point.
 *
 * The routes deliberately cover all four response shapes §8 requires a provider to handle —
 * binary, URL, base64 and JSON — so those code paths are exercised by the demo rather than
 * only by unit tests.
 *
 * Unauthenticated on purpose: it stands in for a THIRD-PARTY API, which would not share this
 * application's API keys. It is mounted only when MOCK_DOCUMENT_API=true and it reads
 * nothing — every response is generated from the path parameters alone, so there is no data
 * here to expose.
 */
@ApiTags('Mock Document API (demo)')
@Controller('documents')
export class MockDocumentApiController {
  /** Whether the demo document API is mounted at all. Off unless explicitly enabled. */
  static enabled(): boolean {
    return process.env.MOCK_DOCUMENT_API === 'true';
  }

  /**
   * Refuses every request unless MOCK_DOCUMENT_API=true.
   *
   * Checked per request rather than by leaving the controller unregistered, so the switch
   * cannot be defeated by a module being imported somewhere unexpected. A disabled demo API
   * is indistinguishable from one that was never deployed.
   */
  private assertEnabled(): void {
    if (!MockDocumentApiController.enabled()) {
      throw new NotFoundException('Cannot GET this path');
    }
  }

  private pdfFor(reference: string, kind: string): Buffer {
    return buildSamplePdf({
      title: `${kind} ${reference}`,
      lines: [
        'Odoovations — demonstration document',
        '',
        `Reference: ${reference}`,
        `Type: ${kind}`,
        `Generated: ${new Date().toISOString()}`,
        '',
        'This is sample data generated by the mock document API',
        'for the Phase 1 WhatsApp delivery demonstration.',
        'It does not represent a real transaction.',
      ],
    });
  }

  @Get('invoices/:invoiceId/pdf')
  @Public()
  @ApiOperation({ summary: 'Demo: a sales invoice as raw PDF bytes (responseFormat "binary")' })
  @Header('content-type', 'application/pdf')
  invoicePdf(@Param('invoiceId') invoiceId: string, @Res() res: Response): void {
    this.assertEnabled();
    const pdf = this.pdfFor(invoiceId, 'Invoice');
    res.setHeader('content-disposition', `attachment; filename="${invoiceId}.pdf"`);
    res.setHeader('content-length', String(pdf.length));
    res.end(pdf);
  }

  @Get('statements/:partyId/json')
  @Public()
  @ApiOperation({ summary: 'Demo: a statement as JSON carrying base64 (responseFormat "json")' })
  statementJson(@Param('partyId') partyId: string): Record<string, unknown> {
    this.assertEnabled();
    const pdf = this.pdfFor(partyId, 'Statement');
    return {
      ok: true,
      data: { filename: `statement-${partyId}.pdf`, mimeType: 'application/pdf', content: pdf.toString('base64') },
    };
  }

  @Get('receipts/:receiptId/base64')
  @Public()
  @ApiOperation({ summary: 'Demo: a receipt as a bare base64 body (responseFormat "base64")' })
  @Header('content-type', 'text/plain')
  receiptBase64(@Param('receiptId') receiptId: string): string {
    this.assertEnabled();
    return this.pdfFor(receiptId, 'Receipt').toString('base64');
  }

  /**
   * Returns a URL the worker must then download, which is the shape that most often hides a
   * bug: the first response succeeds and the document arrives from somewhere else entirely.
   */
  @Get('delivery-notes/:noteId/url')
  @Public()
  @ApiOperation({ summary: 'Demo: a URL to fetch (responseFormat "url")' })
  @Header('content-type', 'text/plain')
  deliveryNoteUrl(@Param('noteId') noteId: string): string {
    this.assertEnabled();
    const base = process.env.MOCK_DOCUMENT_API_BASE ?? `http://127.0.0.1:${process.env.PORT ?? 2785}`;
    return `${base}/api/documents/invoices/${encodeURIComponent(noteId)}/pdf`;
  }

  /**
   * Failure modes, so the demo can show the guards working rather than only assert them.
   *
   * `html` is the one that matters: a 200 response carrying an error page. Without the
   * signature check in §8 that page is delivered to a customer as a .pdf.
   */
  @Get('broken/:mode')
  @Public()
  @ApiOperation({ summary: 'Demo: deliberate bad responses (html | empty | huge | notfound | slow)' })
  async broken(
    @Param('mode') mode: string,
    @Query('delay') delay: string | undefined,
    @Res() res: Response,
  ): Promise<void> {
    this.assertEnabled();
    switch (mode) {
      case 'html':
        res.setHeader('content-type', 'application/pdf');
        res.end('<!doctype html><html><body><h1>502 Bad Gateway</h1></body></html>');
        return;
      case 'empty':
        res.setHeader('content-type', 'application/pdf');
        res.end(Buffer.alloc(0));
        return;
      case 'huge':
        res.setHeader('content-type', 'application/pdf');
        res.end(Buffer.concat([Buffer.from('%PDF-'), Buffer.alloc(12 * 1024 * 1024, 0x20)]));
        return;
      case 'slow':
        await new Promise(resolve => setTimeout(resolve, Number(delay ?? 60_000)));
        res.setHeader('content-type', 'application/pdf');
        res.end(this.pdfFor('SLOW', 'Invoice'));
        return;
      default:
        throw new NotFoundException('No such document');
    }
  }
}
